---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Start a target server
      with_list: "{{ molecule_yml.platforms  }}"
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: "started"
        container_default_behavior: no_defaults
        auto_remove: false
        detach: true
        privileged: "{{ item.privileged | default(false) | bool }}"
        command: "{{ item.command | default(omit) }}"
        tty: true
        tmpfs:
          - /run
          - /tmp
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
