---
# テスト用ターゲットサーバを破棄します。
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Remove target container
      with_list: "{{ molecule_yml.platforms  }}"
      community.docker.docker_container:
        name: "{{ item.name }}"
        container_default_behavior: no_defaults
        state: absent
