---
driver:
  name: delegated

platforms:

  - name: ubuntu22
    image: docker.io/showtatsu/ansible-target:ubuntu-22.04-systemd
    groups:
      - target
    privileged: true


provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        vars:
          ansible_connection: docker

verifier:
  name: ansible

dependency:
  name: galaxy

role_name_check: 0

lint: |
  set -e
  yamllint .
  ansible-lint
